### ISSUE TITLE
 load NvJpeg not stable

### ISSUE THREAD

**Issue by Gotta-C** [UsingNet/nvjpeg-python#1]
nj = NvJpeg()

SystemError: <class 'nvjpeg.NvJpeg'> returned NULL without setting an error
run above 5 times and succeed once

TurboJPEG encode  0.004872s per image as 1 cpu core
NvJpeg encode 0.001235s per image as 1 gpu

test encode is normal and can the lib support ThreadPoolExecutor or how to modify in nvjpeg-python.c to support that.

**Comment by ald2004** [comment]
the same problem when run with multiprocessing, i guess nvjpeg handler needs some resource which conflict with other processes.

**Comment by zengohm** [comment]
Thanks @Gotta-C @ald2004 .
I have fixed this bug in version 0.0.8.
You can try the test file [tests/test-with-multiprocessing.py](https://github.com/UsingNet/nvjpeg-python/blob/master/tests/test-with-multiprocessing.py) that tests for running with ThreadPoolExecutor.

**Comment by chrischengis** [comment]
I have version 0.0.9.
I am still getting this error when running with multiprocessing:
File "/opt/conda/lib/python3.8/site-packages/torchvision/datasets/folder.py", line 138, in __init__
    self.nj = NvJpeg()
SystemError: <class 'nvjpeg.NvJpeg'> returned NULL without setting an error

I ran tests/test-with-multiprocessing.py, and it passed.
